# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  schedule:
    - cron: "*/5 * * * *"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: -X POST -d {} https://api.netlify.com/build_hooks/5e6bf671fb5f313507961732
